issuer: https://token.actions.githubusercontent.com
subject: repo:shopware/octo-sts-action:pull_request
claim_pattern:
  workflow_ref: shopware/octo-sts-action/\.github/workflows/use-action\.yaml@refs/heads/main

permissions:
  contents: read
